### ISSUE TITLE
Optional field param

### ISSUE THREAD

**Issue by tomchambers2** [times/data-validator#29]
Would be nice to validate only some of the objects propertys. For example, when accepting a file upload, extra metadata is provided which will not be used. The library may change or the amount of data provided may be large so difficult to add every possible property, so it would be useful to be able to be permissive on what extra is provided if it will simply be discarded.

**Comment by elliotdavies** [comment]
@tomchambers2 I think this is possible already 😄 The default `objectValidator` is strict, meaning it doesn't allow empty fields, but you can construct a non-strict version that will only check the fields in the schema. https://github.com/times/data-validator/issues/15 ought to resolve this by making that clearer.

**Comment by tomchambers2** [comment]
👍
